INSERT INTO Players (name) VALUES ('Egor Ivanov');
INSERT INTO Players (name) VALUES ('Katya Petrova');
INSERT INTO Players (name) VALUES ('Misha Sidorov');
INSERT INTO Players (name) VALUES ('Lenya Kravtsov');
INSERT INTO Players (name) VALUES ('Polina Smirnova');
INSERT INTO Players (name) VALUES ('Sanya Ivanov');
INSERT INTO Players (name) VALUES ('Elena Petrova');
INSERT INTO Players (name) VALUES ('K. Voronov');
INSERT INTO Players (name) VALUES ('Lena Kuznetsova');
INSERT INTO Players (name) VALUES ('Danek Pavlov');
INSERT INTO Players (name) VALUES ('Nadya Frolova');
INSERT INTO Players (name) VALUES ('Sanya Mironov');
INSERT INTO Players (name) VALUES ('Olya Solovyeva');
INSERT INTO Players (name) VALUES ('Ivan Karpov');
INSERT INTO Players (name) VALUES ('Tanya Guseva');
INSERT INTO Players (name) VALUES ('Veronika Smolenskaya');
INSERT INTO Players (name) VALUES ('Petr Mikhailov');

INSERT INTO Matches (player1, player2, winner) VALUES (1, 2, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO Matches (player1, player2, winner) VALUES (5, 1, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (2, 4, 4);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 5, 3);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 2, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 4, 4);
INSERT INTO Matches (player1, player2, winner) VALUES (5, 6, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO Matches (player1, player2, winner) VALUES (9, 10, 10);
INSERT INTO Matches (player1, player2, winner) VALUES (11, 12, 11);
INSERT INTO Matches (player1, player2, winner) VALUES (13, 14, 13);
INSERT INTO Matches (player1, player2, winner) VALUES (15, 16, 16);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 3, 1);
INSERT INTO Matches (player1, player2, winner) VALUES (2, 4, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (5, 7, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (6, 8, 6);
INSERT INTO Matches (player1, player2, winner) VALUES (9, 11, 11);
