INSERT INTO Players (name) VALUES ('E. Ivanov');
INSERT INTO Players (name) VALUES ('K. Petrova');
INSERT INTO Players (name) VALUES ('M. Sidorov');
INSERT INTO Players (name) VALUES ('L. Kravtsov');
INSERT INTO Players (name) VALUES ('P. Smirnova');
INSERT INTO Players (name) VALUES ('A. Ivanov');
INSERT INTO Players (name) VALUES ('E. Petrova');
INSERT INTO Players (name) VALUES ('K. Voronov');
INSERT INTO Players (name) VALUES ('L. Kuznetsova');
INSERT INTO Players (name) VALUES ('D. Pavlov');
INSERT INTO Players (name) VALUES ('N. Frolova');
INSERT INTO Players (name) VALUES ('S. Mironov');
INSERT INTO Players (name) VALUES ('O. Solovyeva');
INSERT INTO Players (name) VALUES ('I. Karpov');
INSERT INTO Players (name) VALUES ('T. Guseva');
INSERT INTO Players (name) VALUES ('V. Smolenskaya');
INSERT INTO Players (name) VALUES ('P. Mikhailov');

INSERT INTO Matches (player1, player2, winner) VALUES (1, 2, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO Matches (player1, player2, winner) VALUES (5, 1, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (2, 4, 4);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 5, 3);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 2, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 4, 4);
INSERT INTO Matches (player1, player2, winner) VALUES (5, 6, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO Matches (player1, player2, winner) VALUES (9, 10, 10);
INSERT INTO Matches (player1, player2, winner) VALUES (11, 12, 11);
INSERT INTO Matches (player1, player2, winner) VALUES (13, 14, 13);
INSERT INTO Matches (player1, player2, winner) VALUES (15, 16, 16);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 3, 1);
INSERT INTO Matches (player1, player2, winner) VALUES (2, 4, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (5, 7, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (6, 8, 6);
INSERT INTO Matches (player1, player2, winner) VALUES (9, 11, 11);
